[package]
name = "lv2xdo"
version = "0.1.0"
authors = ["Philipp Keck <philipp@philippkeck.de>"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lv2 = "0.6.0"
wmidi = "3.1.0" # Should match the version in lv2-midi
libxdo-sys = "0.11.0"
